# Generated by Django 2.0.2 on 2018-02-12 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='InterventionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='interventioncategory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interventions.Location'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interventions.InterventionCategory'),
        ),
    ]
