# Generated by Django 2.0.2 on 2018-02-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interventioncategory',
            options={'verbose_name_plural': 'Intervention categories'},
        ),
        migrations.AddField(
            model_name='intervention',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='intervention',
            name='methodology',
            field=models.CharField(choices=[('n', 'None'), ('rct', 'RCT'), ('iv', 'Instrumental Variables'), ('rd', 'Regression Discontinuity')], default='n', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervention',
            name='status',
            field=models.CharField(choices=[('n', 'None'), ('pl', 'Planning'), ('pr', 'In Progress'), ('co', 'Complete')], default='n', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervention',
            name='type',
            field=models.CharField(choices=[('n', 'None'), ('rb', 'Rebate'), ('te', 'Tax Expenditure'), ('co', 'Communication'), ('pa', 'Predictive Analysis')], default='n', max_length=5),
            preserve_default=False,
        ),
    ]
