# Generated by Django 2.0.2 on 2018-02-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0002_auto_20180213_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='anual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='number_participants',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='number_replicated',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='years_active',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='methodology',
            field=models.CharField(choices=[('n', 'None'), ('rct', 'RCT'), ('iv', 'Instrumental Variables'), ('rd', 'Regression Discontinuity')], default='n', max_length=5),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='status',
            field=models.CharField(choices=[('n', 'None'), ('pl', 'Planning'), ('pr', 'In Progress'), ('co', 'Complete')], default='n', max_length=5),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='type',
            field=models.CharField(choices=[('n', 'None'), ('rb', 'Rebate'), ('te', 'Tax Expenditure'), ('co', 'Communication'), ('pa', 'Predictive Analysis')], default='n', max_length=5),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
    ]
