# Generated by Django 2.0.2 on 2018-02-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0003_auto_20180214_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='contact',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='cost_per_household',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='funding_source',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='number_incidents',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Number of crime incidents'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='number_iterations',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
