# Generated by Django 2.0.2 on 2018-02-16 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0004_auto_20180214_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=300, verbose_name='Name')),
                ('email', models.EmailField(max_length=300)),
                ('program_name', models.CharField(max_length=300)),
                ('more_information', models.TextField(blank=True, max_length=2000, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
