# Generated by Django 2.0.2 on 2018-02-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0005_casestudy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
