# Generated by Django 2.0.2 on 2018-02-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0006_auto_20180216_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'verbose_name_plural': 'Case studies'},
        ),
        migrations.AddField(
            model_name='intervention',
            name='csv_data',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
