# Generated by Django 2.0.2 on 2018-04-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20180409_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='search_keywords',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
