# Generated by Django 2.0.2 on 2018-03-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='fips_code',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='FIPS Code (2 digits for state, 5 digits for county, 7 digits for a place)', max_length=7, null=True),
        ),
    ]
